//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployJobProfile
    {
        public string Employ_ID { get; set; }
        public string Career_ID { get; set; }
        public Nullable<System.DateTime> date_started { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        public virtual JobOfDep JobOfDep { get; set; }
        public virtual HistoryEmployee HistoryEmployee { get; set; }
    }
}
