//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FinalHRMEntities6 : DbContext
    {
        public FinalHRMEntities6()
            : base("name=FinalHRMEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<EmployeeNow> EmployeeNows { get; set; }
        public virtual DbSet<EmployJobProfile> EmployJobProfiles { get; set; }
        public virtual DbSet<HistoryEmployee> HistoryEmployees { get; set; }
        public virtual DbSet<HistoryTakePartIn> HistoryTakePartIns { get; set; }
        public virtual DbSet<JobOfDep> JobOfDeps { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<TakePartInNow> TakePartInNows { get; set; }
    
        public virtual int del_EmplowNow(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_EmplowNow", idParameter);
        }
    
        public virtual int del_TakePartInNow(string projid, string emid)
        {
            var projidParameter = projid != null ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(string));
    
            var emidParameter = emid != null ?
                new ObjectParameter("emid", emid) :
                new ObjectParameter("emid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("del_TakePartInNow", projidParameter, emidParameter);
        }
    
        public virtual ObjectResult<Dep_Search_Result> Dep_Search(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Dep_Search_Result>("Dep_Search", searchParameter);
        }
    
        public virtual ObjectResult<Employ_Search_Result> Employ_Search(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employ_Search_Result>("Employ_Search", searchParameter);
        }
    
        public virtual ObjectResult<Employ_Search_History_Result> Employ_Search_History(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Employ_Search_History_Result>("Employ_Search_History", searchParameter);
        }
    
        public virtual int new_acc(string acc, string pass)
        {
            var accParameter = acc != null ?
                new ObjectParameter("acc", acc) :
                new ObjectParameter("acc", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_acc", accParameter, passParameter);
        }
    
        public virtual int new_Dep(string dep_id, string dep_name)
        {
            var dep_idParameter = dep_id != null ?
                new ObjectParameter("dep_id", dep_id) :
                new ObjectParameter("dep_id", typeof(string));
    
            var dep_nameParameter = dep_name != null ?
                new ObjectParameter("dep_name", dep_name) :
                new ObjectParameter("dep_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_Dep", dep_idParameter, dep_nameParameter);
        }
    
        public virtual int new_Employee(string emid, string emname, Nullable<System.DateTime> dob, string sex, string email, string phone, Nullable<System.DateTime> join, string career, Nullable<int> salary)
        {
            var emidParameter = emid != null ?
                new ObjectParameter("emid", emid) :
                new ObjectParameter("emid", typeof(string));
    
            var emnameParameter = emname != null ?
                new ObjectParameter("emname", emname) :
                new ObjectParameter("emname", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var joinParameter = join.HasValue ?
                new ObjectParameter("join", join) :
                new ObjectParameter("join", typeof(System.DateTime));
    
            var careerParameter = career != null ?
                new ObjectParameter("Career", career) :
                new ObjectParameter("Career", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_Employee", emidParameter, emnameParameter, dobParameter, sexParameter, emailParameter, phoneParameter, joinParameter, careerParameter, salaryParameter);
        }
    
        public virtual int new_Jobs(string jobid, string jobname)
        {
            var jobidParameter = jobid != null ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(string));
    
            var jobnameParameter = jobname != null ?
                new ObjectParameter("jobname", jobname) :
                new ObjectParameter("jobname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_Jobs", jobidParameter, jobnameParameter);
        }
    
        public virtual int new_Profile(string emid, string career, Nullable<System.DateTime> datestart, Nullable<System.DateTime> dateend)
        {
            var emidParameter = emid != null ?
                new ObjectParameter("emid", emid) :
                new ObjectParameter("emid", typeof(string));
    
            var careerParameter = career != null ?
                new ObjectParameter("career", career) :
                new ObjectParameter("career", typeof(string));
    
            var datestartParameter = datestart.HasValue ?
                new ObjectParameter("datestart", datestart) :
                new ObjectParameter("datestart", typeof(System.DateTime));
    
            var dateendParameter = dateend.HasValue ?
                new ObjectParameter("dateend", dateend) :
                new ObjectParameter("dateend", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_Profile", emidParameter, careerParameter, datestartParameter, dateendParameter);
        }
    
        public virtual int new_proj(string projid, string projname, Nullable<System.DateTime> date, string status, string note)
        {
            var projidParameter = projid != null ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(string));
    
            var projnameParameter = projname != null ?
                new ObjectParameter("projname", projname) :
                new ObjectParameter("projname", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_proj", projidParameter, projnameParameter, dateParameter, statusParameter, noteParameter);
        }
    
        public virtual int new_tpi(string projid, string empid, Nullable<System.DateTime> date)
        {
            var projidParameter = projid != null ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(string));
    
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("new_tpi", projidParameter, empidParameter, dateParameter);
        }
    
        public virtual ObjectResult<output_AllDep_Result> output_AllDep()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_AllDep_Result>("output_AllDep");
        }
    
        public virtual ObjectResult<output_AllJob_Result> output_AllJob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_AllJob_Result>("output_AllJob");
        }
    
        public virtual ObjectResult<output_AllJoD_Result> output_AllJoD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_AllJoD_Result>("output_AllJoD");
        }
    
        public virtual ObjectResult<output_AllProfile_Result> output_AllProfile()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_AllProfile_Result>("output_AllProfile");
        }
    
        public virtual ObjectResult<output_AllProj_Result> output_AllProj()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_AllProj_Result>("output_AllProj");
        }
    
        public virtual ObjectResult<output_Employ_Dep_Result> output_Employ_Dep(string depid)
        {
            var depidParameter = depid != null ?
                new ObjectParameter("depid", depid) :
                new ObjectParameter("depid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_Employ_Dep_Result>("output_Employ_Dep", depidParameter);
        }
    
        public virtual ObjectResult<output_Employ_Job_Result> output_Employ_Job(string jobid)
        {
            var jobidParameter = jobid != null ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_Employ_Job_Result>("output_Employ_Job", jobidParameter);
        }
    
        public virtual ObjectResult<output_Employ_Job_History_Result> output_Employ_Job_History(string employ)
        {
            var employParameter = employ != null ?
                new ObjectParameter("employ", employ) :
                new ObjectParameter("employ", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_Employ_Job_History_Result>("output_Employ_Job_History", employParameter);
        }
    
        public virtual ObjectResult<output_Employ_Proj_Result> output_Employ_Proj(string projid)
        {
            var projidParameter = projid != null ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_Employ_Proj_Result>("output_Employ_Proj", projidParameter);
        }
    
        public virtual ObjectResult<output_Employnow_Result> output_Employnow()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_Employnow_Result>("output_Employnow");
        }
    
        public virtual ObjectResult<output_HistoryEmploy_Result> output_HistoryEmploy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_HistoryEmploy_Result>("output_HistoryEmploy");
        }
    
        public virtual ObjectResult<output_TPIHistory_Result> output_TPIHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_TPIHistory_Result>("output_TPIHistory");
        }
    
        public virtual ObjectResult<output_TPINow_Result> output_TPINow()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<output_TPINow_Result>("output_TPINow");
        }
    
        public virtual ObjectResult<Profile_Search_Result> Profile_Search(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profile_Search_Result>("Profile_Search", searchParameter);
        }
    
        public virtual ObjectResult<Proj_Search_Result> Proj_Search(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proj_Search_Result>("Proj_Search", searchParameter);
        }
    
        public virtual ObjectResult<TPI_His_Search_Result> TPI_His_Search(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TPI_His_Search_Result>("TPI_His_Search", searchParameter);
        }
    
        public virtual int update_dep(string depid, string depname, string manager)
        {
            var depidParameter = depid != null ?
                new ObjectParameter("depid", depid) :
                new ObjectParameter("depid", typeof(string));
    
            var depnameParameter = depname != null ?
                new ObjectParameter("depname", depname) :
                new ObjectParameter("depname", typeof(string));
    
            var managerParameter = manager != null ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_dep", depidParameter, depnameParameter, managerParameter);
        }
    
        public virtual int update_empl(string emid, string emname, Nullable<System.DateTime> dob, string sex, string email, string phone, Nullable<System.DateTime> join, string career, Nullable<int> salary)
        {
            var emidParameter = emid != null ?
                new ObjectParameter("emid", emid) :
                new ObjectParameter("emid", typeof(string));
    
            var emnameParameter = emname != null ?
                new ObjectParameter("emname", emname) :
                new ObjectParameter("emname", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var sexParameter = sex != null ?
                new ObjectParameter("sex", sex) :
                new ObjectParameter("sex", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("phone", phone) :
                new ObjectParameter("phone", typeof(string));
    
            var joinParameter = join.HasValue ?
                new ObjectParameter("join", join) :
                new ObjectParameter("join", typeof(System.DateTime));
    
            var careerParameter = career != null ?
                new ObjectParameter("Career", career) :
                new ObjectParameter("Career", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_empl", emidParameter, emnameParameter, dobParameter, sexParameter, emailParameter, phoneParameter, joinParameter, careerParameter, salaryParameter);
        }
    
        public virtual int update_job(string jobid, string jobname)
        {
            var jobidParameter = jobid != null ?
                new ObjectParameter("jobid", jobid) :
                new ObjectParameter("jobid", typeof(string));
    
            var jobnameParameter = jobname != null ?
                new ObjectParameter("jobname", jobname) :
                new ObjectParameter("jobname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_job", jobidParameter, jobnameParameter);
        }
    
        public virtual int update_Proj(string projid, string projname, Nullable<System.DateTime> date, string status, string note)
        {
            var projidParameter = projid != null ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(string));
    
            var projnameParameter = projname != null ?
                new ObjectParameter("projname", projname) :
                new ObjectParameter("projname", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_Proj", projidParameter, projnameParameter, dateParameter, statusParameter, noteParameter);
        }
    
        public virtual int update_TPI(string projid, string empid, Nullable<System.DateTime> date, string note)
        {
            var projidParameter = projid != null ?
                new ObjectParameter("projid", projid) :
                new ObjectParameter("projid", typeof(string));
    
            var empidParameter = empid != null ?
                new ObjectParameter("empid", empid) :
                new ObjectParameter("empid", typeof(string));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            var noteParameter = note != null ?
                new ObjectParameter("Note", note) :
                new ObjectParameter("Note", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_TPI", projidParameter, empidParameter, dateParameter, noteParameter);
        }
    }
}
