//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HistoryEmployee()
        {
            this.EmployJobProfiles = new HashSet<EmployJobProfile>();
            this.HistoryTakePartIns = new HashSet<HistoryTakePartIn>();
        }
    
        public string Employ_ID { get; set; }
        public string Employ_Name { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public Nullable<System.DateTime> joindate { get; set; }
        public string work_status { get; set; }
        public Nullable<System.DateTime> quitdate { get; set; }
    
        public virtual EmployeeNow EmployeeNow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployJobProfile> EmployJobProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryTakePartIn> HistoryTakePartIns { get; set; }
    }
}
