//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalHRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOfDep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobOfDep()
        {
            this.EmployeeNows = new HashSet<EmployeeNow>();
            this.EmployJobProfiles = new HashSet<EmployJobProfile>();
        }
    
        public string id { get; set; }
        public string Dep_ID { get; set; }
        public string Job_ID { get; set; }
        public string name { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeNow> EmployeeNows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployJobProfile> EmployJobProfiles { get; set; }
        public virtual Job Job { get; set; }
    }
}
